### ISSUE TITLE
Auth problem for CRUD post

### ISSUE THREAD

**Issue by lolimilkita-ccd** [lolimilkita/coba-laravel#19]
User bisa melihat,edit, deleted (CRUD) post user lainnya hanya dengan menuliskan slug post milik mereka ke http.

**Comment by lolimilkita** [comment]
Tambahin kode dibawah ke DashboardPostController di method show sama edit.

if($post->author->id !== auth()->user()->id) {
      abort(403);
}

Atau sudah saya fix di commit [Fix issue] (https://github.com/lolimilkita/coba-laravel/commit/b4c8eff1cd1aabc7fdc436e39ccb4549a62ab2e4)
